version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - PORT=8080
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
